# Generated by Django 5.1 on 2026-02-27 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID пользователя в Telegram', unique=True)),
                ('username', models.CharField(blank=True, help_text='Username в Telegram (@username)', max_length=100)),
                ('first_name', models.CharField(help_text='Имя в Telegram', max_length=200)),
                ('last_name', models.CharField(blank=True, help_text='Фамилия в Telegram', max_length=200)),
                ('photo_url', models.URLField(blank=True, help_text='Ссылка на аватар в Telegram')),
                ('language_code', models.CharField(blank=True, help_text='Язык Telegram клиента', max_length=10)),
                ('is_premium', models.BooleanField(default=False, help_text='Telegram Premium подписка')),
                ('auth_date', models.DateTimeField(help_text='Дата последней авторизации через initData')),
                ('auth_hash', models.CharField(help_text='Последний валидный hash initData', max_length=64)),
                ('theme_params', models.JSONField(default=dict, help_text='Параметры темы Telegram клиента')),
                ('app_opens_count', models.IntegerField(default=0, help_text='Сколько раз открывал Mini App')),
                ('last_app_open', models.DateTimeField(blank=True, help_text='Последний раз открывал', null=True)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Время в Mini App (секунды)')),
                ('account_linked_at', models.DateTimeField(blank=True, help_text='Когда привязан к аккаунту DOD', null=True)),
                ('link_method', models.CharField(blank=True, choices=[('auto', 'Автоматически'), ('email', 'Через email'), ('phone', 'Через телефон'), ('existing', 'Через существующий аккаунт'), ('new', 'Новый аккаунт')], help_text='Метод привязки аккаунта', max_length=20)),
                ('bot_notifications_enabled', models.BooleanField(default=True, help_text='Разрешил уведомления от бота')),
                ('notification_preferences', models.JSONField(default=dict, help_text='Настройки уведомлений')),
                ('referred_by_deeplink', models.CharField(blank=True, help_text='Deeplink параметр при первом /start', max_length=100)),
                ('device_info', models.JSONField(default=dict, help_text='Информация об устройстве')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Связанный пользователь DOD', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
        migrations.CreateModel(
            name='MiniAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Генерируется при каждом открытии', max_length=64, unique=True)),
                ('init_data_hash', models.CharField(help_text='Hash для валидации', max_length=64)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('tdesktop', 'Desktop'), ('web', 'Web Telegram'), ('macos', 'macOS')], help_text='Платформа Telegram клиента', max_length=20)),
                ('telegram_version', models.CharField(help_text='Версия Telegram клиента', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('pages_visited', models.JSONField(default=list, help_text='Посещённые страницы')),
                ('actions_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='miniapp.telegramuser')),
            ],
            options={
                'verbose_name': 'Сессия Mini App',
                'verbose_name_plural': 'Сессии Mini App',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id'], name='miniapp_tel_telegra_1a6f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['user'], name='miniapp_tel_user_id_da0c28_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['created_at'], name='miniapp_tel_created_6166e6_idx'),
        ),
        migrations.AddIndex(
            model_name='miniappsession',
            index=models.Index(fields=['telegram_user', 'is_active'], name='miniapp_min_telegra_9bf8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='miniappsession',
            index=models.Index(fields=['started_at'], name='miniapp_min_started_7ab142_idx'),
        ),
    ]
