# Generated by Django 5.1 on 2026-02-27 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('permissions', models.JSONField(default=dict, verbose_name='Права доступа')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень доступа')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Роль администратора',
                'verbose_name_plural': 'Роли администраторов',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_permissions', models.JSONField(default=dict, verbose_name='Индивидуальные права')),
                ('receive_admin_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления админа')),
                ('notification_channels', models.JSONField(default=dict, help_text='{"email": true, "telegram": true, "dashboard": true}', verbose_name='Каналы уведомлений')),
                ('work_schedule', models.JSONField(default=dict, help_text='{"mon": {"start": "09:00", "end": "18:00"}, ...}', verbose_name='График работы')),
                ('total_actions', models.IntegerField(default=0, verbose_name='Всего действий')),
                ('last_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее действие')),
                ('ip_whitelist', models.JSONField(default=list, verbose_name='Белый список IP')),
                ('is_admin_active', models.BooleanField(default=True, verbose_name='Активен как админ')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирован')),
                ('deactivated_reason', models.TextField(blank=True, verbose_name='Причина деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.adminrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Профиль администратора',
                'verbose_name_plural': 'Профили администраторов',
            },
        ),
    ]
