# Generated by Django 5.1 on 2026-02-26 17:39

import apps.accounts.managers
import apps.accounts.models
import apps.accounts.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='accounts_lo_user_id_a5a726_idx',
            old_name='accounts_loginhistory_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='accounts_lo_ip_addr_142937_idx',
            old_name='accounts_loginhistory_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_usernam_c0ea66_idx',
            old_name='accounts_us_username_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_phone_f54457_idx',
            old_name='accounts_us_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_referra_2cbfb5_idx',
            old_name='accounts_us_referral_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_created_4734df_idx',
            old_name='accounts_us_created_idx',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=apps.accounts.models.email_token_expires_default),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='expires_at',
            field=models.DateTimeField(default=apps.accounts.models.phone_token_expires_default),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.avatar_upload_path, validators=[apps.accounts.validators.validate_avatar_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default=apps.accounts.models.notification_default),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
