# Generated by Django 5.1 on 2026-02-27 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=50)),
                ('action_category', models.CharField(max_length=50)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Действие администратора',
                'verbose_name_plural': 'Действия администраторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('general', 'Общее'), ('bet_result', 'Результат ставки'), ('deposit', 'Депозит'), ('withdrawal', 'Вывод'), ('kyc', 'Верификация'), ('security', 'Безопасность'), ('referral', 'Рефералы'), ('promotion', 'Акции'), ('ticket_created', 'Тикет создан'), ('ticket_reply', 'Ответ на тикет'), ('ticket_resolved', 'Тикет решён'), ('ticket_reopened', 'Тикет переоткрыт'), ('payout_completed', 'Выплата завершена'), ('payout_rejected', 'Выплата отклонена'), ('partner_tier_up', 'Повышение уровня партнёра'), ('partner_tier_down', 'Понижение уровня партнёра'), ('new_referral', 'Новый реферал'), ('referral_commission', 'Комиссия от реферала'), ('referral_qualified', 'Реферал квалифицирован')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_user', 'created_at'], name='accounts_ad_admin_u_74a07d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_user'], name='accounts_ad_target__833e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['module'], name='accounts_ad_module_c7c716_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type'], name='accounts_ad_action__3ff7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='accounts_no_user_id_cabb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='accounts_no_notific_6d2f3e_idx'),
        ),
    ]
