# Generated by Django 5.1 on 2026-02-27 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminactionlog_notification_delete_linkedaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram'), ('phone', 'Телефон')], max_length=20)),
                ('provider_id', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('provider_username', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_avatar', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привязанный аккаунт',
                'verbose_name_plural': 'Привязанные аккаунты',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_li_user_id_fef61b_idx'), models.Index(fields=['provider', 'provider_id'], name='accounts_li_provide_a6a7cf_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='TOTP', max_length=50)),
                ('secret', models.CharField(max_length=32)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP устройство',
                'verbose_name_plural': 'TOTP устройства',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'confirmed'], name='accounts_to_user_id_53a9c2_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
