# Generated by Django 5.1 on 2026-02-27 02:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('crash_enabled', models.BooleanField(default=True)),
                ('crash_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('crash_max_bet', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('crash_house_edge', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('crash_max_multiplier', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('crash_round_wait_time', models.IntegerField(default=10)),
                ('slots_enabled', models.BooleanField(default=True)),
                ('slots_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('slots_max_bet', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('slots_rtp', models.DecimalField(decimal_places=2, default=Decimal('96.00'), max_digits=5)),
                ('roulette_enabled', models.BooleanField(default=True)),
                ('roulette_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('roulette_max_bet', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('mines_enabled', models.BooleanField(default=True)),
                ('mines_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('mines_max_bet', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('dice_enabled', models.BooleanField(default=True)),
                ('dice_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('dice_max_bet', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('plinko_enabled', models.BooleanField(default=True)),
                ('plinko_min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('plinko_max_bet', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('max_concurrent_games', models.IntegerField(default=5)),
                ('show_recent_bets', models.BooleanField(default=True)),
                ('show_big_wins', models.BooleanField(default=True)),
                ('big_win_threshold_usd', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
            options={
                'verbose_name': 'Настройки казино',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('house_edge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rtp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('max_win_multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('total_bets', models.BigIntegerField(default=0)),
                ('total_wagered_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_won_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип игры',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CrashGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_id', models.CharField(max_length=50, unique=True)),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание ставок'), ('running', 'Идёт'), ('crashed', 'Упал')], default='waiting', max_length=20)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('chain_hash', models.CharField(max_length=64)),
                ('players_count', models.IntegerField(default=0)),
                ('total_bet', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('crashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casino.crashgame')),
            ],
            options={
                'verbose_name': 'Раунд Crash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('bet_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bet_amount_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('win_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('win_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('won', 'Выигрыш'), ('lost', 'Проигрыш'), ('cashout', 'Кэшаут'), ('cancelled', 'Отменена')], default='active', max_length=20)),
                ('game_data', models.JSONField(default=dict)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(max_length=64)),
                ('nonce', models.BigIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_session', to='wallet.transaction')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_games', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
                ('win_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_session', to='wallet.transaction')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.gametype')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrashBet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('auto_cashout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cashout_at', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'В игре'), ('cashed_out', 'Забрал'), ('busted', 'Не успел')], default='active', max_length=20)),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crash_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='casino.crashgame')),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='casino.gamesession')),
            ],
            options={
                'verbose_name': 'Ставка в Crash',
            },
        ),
        migrations.CreateModel(
            name='UserSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(max_length=64)),
                ('nonce', models.BigIntegerField(default=0)),
                ('previous_server_seed', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_server_seed_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_seed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed пользователя',
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'started_at'], name='casino_game_user_id_a0073b_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game_type', 'started_at'], name='casino_game_game_ty_6084d5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status'], name='casino_game_status_9efbca_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game_id'], name='casino_game_game_id_2830e7_idx'),
        ),
    ]
