# Generated by Django 5.1 on 2026-02-27 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['partner', 'created_at'], name='referral_co_partner_35adf3_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['partner', 'status'], name='referral_co_partner_2e3df9_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['referral', 'period_start'], name='referral_co_referra_9d4c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['commission_type'], name='referral_co_commiss_c1721c_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'created_at'], name='referral_co_status_4f8cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerpayout',
            index=models.Index(fields=['partner', 'status'], name='referral_pa_partner_466eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerpayout',
            index=models.Index(fields=['status', 'created_at'], name='referral_pa_status_e63fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='promolink',
            index=models.Index(fields=['partner', 'is_active'], name='referral_pr_partner_90f8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['partner', 'status'], name='referral_re_partner_7c8d72_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['partner', 'created_at'], name='referral_re_partner_69b95d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['partner', 'is_qualified'], name='referral_re_partner_e81416_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'created_at'], name='referral_re_status_9a8adb_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['level'], name='referral_re_level_564000_idx'),
        ),
    ]
