# Generated by Django 5.1 on 2026-02-27 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('articles_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('priority', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_response_minutes', models.IntegerField()),
                ('resolution_minutes', models.IntegerField()),
                ('chat_response_seconds', models.IntegerField()),
                ('business_hours_only', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Настройки SLA',
            },
        ),
        migrations.CreateModel(
            name='FAQArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('question_en', models.CharField(blank=True, max_length=300)),
                ('answer', models.TextField(max_length=10000)),
                ('answer_en', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('views_count', models.IntegerField(default=0)),
                ('helpful_yes', models.IntegerField(default=0)),
                ('helpful_no', models.IntegerField(default=0)),
                ('related_ticket_categories', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='support.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ статья',
                'ordering': ['-is_pinned', 'sort_order', '-views_count'],
            },
        ),
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger_keywords', models.JSONField()),
                ('trigger_categories', models.JSONField(default=list)),
                ('response_text', models.TextField(max_length=3000)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('times_triggered', models.IntegerField(default=0)),
                ('times_resolved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.faqarticle')),
            ],
            options={
                'verbose_name': 'Автоответ',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('operator', 'Оператор'), ('system', 'Система'), ('bot', 'Автоответ')], max_length=20)),
                ('text', models.TextField(max_length=5000)),
                ('is_system_message', models.BooleanField(default=False)),
                ('system_action', models.CharField(blank=True, max_length=50)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_read_by_user', models.BooleanField(default=False)),
                ('is_read_by_operator', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support/attachments/{ticket_id}/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('is_image', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='support/attachments/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.message')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_status', models.CharField(choices=[('online', 'На линии'), ('busy', 'Занят'), ('away', 'Отошёл'), ('offline', 'Оффлайн')], default='offline', max_length=20)),
                ('max_concurrent_chats', models.IntegerField(default=5)),
                ('current_chats_count', models.IntegerField(default=0)),
                ('current_tickets_count', models.IntegerField(default=0)),
                ('categories', models.JSONField(default=list)),
                ('can_handle_critical', models.BooleanField(default=False)),
                ('can_escalate', models.BooleanField(default=True)),
                ('can_close_tickets', models.BooleanField(default=True)),
                ('can_transfer', models.BooleanField(default=True)),
                ('total_tickets_handled', models.IntegerField(default=0)),
                ('total_chats_handled', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('avg_first_response_seconds', models.IntegerField(default=0)),
                ('avg_resolution_seconds', models.IntegerField(default=0)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль оператора',
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=3000)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_global', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Быстрый ответ',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('finance', 'Финансы и платежи'), ('deposit', 'Проблема с депозитом'), ('withdrawal', 'Проблема с выводом'), ('account', 'Аккаунт и профиль'), ('verification', 'Верификация (KYC)'), ('sport_bet', 'Ставки на спорт'), ('casino', 'Казино'), ('prediction', 'Маркеты предсказаний'), ('referral', 'Партнёрская программа'), ('technical', 'Технические проблемы'), ('security', 'Безопасность'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('other', 'Другое')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидание ответа пользователя'), ('waiting_admin', 'Ожидание ответа оператора'), ('on_hold', 'На удержании'), ('resolved', 'Решён'), ('closed', 'Закрыт'), ('reopened', 'Переоткрыт')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('form', 'Форма на сайте'), ('chat', 'Живой чат'), ('email', 'Email'), ('telegram', 'Telegram'), ('admin', 'Создан администратором')], default='form', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('internal_notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True, max_length=500)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_status', models.CharField(choices=[('waiting', 'Ожидание оператора'), ('active', 'Активный разговор'), ('idle', 'Неактивен'), ('ended', 'Завершён')], default='waiting', max_length=20)),
                ('user_channel_name', models.CharField(blank=True, max_length=255)),
                ('operator_channel_name', models.CharField(blank=True, max_length=255)),
                ('queue_position', models.IntegerField(default=0)),
                ('queue_entered_at', models.DateTimeField(blank=True, null=True)),
                ('operator_joined_at', models.DateTimeField(blank=True, null=True)),
                ('wait_time_seconds', models.IntegerField(default=0)),
                ('messages_count', models.IntegerField(default=0)),
                ('user_typing', models.BooleanField(default=False)),
                ('operator_typing', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, max_length=20)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='support.ticket')),
            ],
            options={
                'verbose_name': 'Чат-сессия',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faqarticle',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='support_faq_categor_6e2daf_idx'),
        ),
        migrations.AddIndex(
            model_name='faqarticle',
            index=models.Index(fields=['is_active', 'views_count'], name='support_faq_is_acti_b88124_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='support_tic_status_08d7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_6ed26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'created_at'], name='support_tic_user_id_8d0c53_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', 'status'], name='support_tic_categor_54255d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='support_tic_ticket__d87f40_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'created_at'], name='support_mes_ticket__b9f841_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='support_mes_sender__62846d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chat_status'], name='support_cha_chat_st_3d0cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['operator', 'chat_status'], name='support_cha_operato_122427_idx'),
        ),
    ]
