# Generated by Django 5.1 on 2026-02-26 17:39

import apps.wallet.models
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('fiat', 'Фиатная'), ('crypto', 'Криптовалюта')], max_length=10)),
                ('decimal_places', models.IntegerField()),
                ('rate_to_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate_updated_at', models.DateTimeField(blank=True, null=True)),
                ('min_deposit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('min_withdrawal', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('max_withdrawal_daily', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('withdrawal_fee_fixed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('conversion_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deposit_enabled', models.BooleanField(default=True)),
                ('is_withdrawal_enabled', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_active'], name='wallet_curr_is_acti_5d4c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_submitted', 'Не подана'), ('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='not_submitted', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Паспорт'), ('national_id', 'ID карта'), ('drivers_license', 'Водительское удостоверение')], max_length=20, null=True)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to=apps.wallet.models.KYCVerification.document_front_path)),
                ('document_back', models.ImageField(blank=True, null=True, upload_to=apps.wallet.models.KYCVerification.document_back_path)),
                ('selfie_with_document', models.ImageField(blank=True, null=True, upload_to=apps.wallet.models.KYCVerification.selfie_upload_path)),
                ('full_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(help_text='Хранится в зашифрованном виде', max_length=50)),
                ('document_number_encrypted', models.BinaryField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('country_of_issue', django_countries.fields.CountryField(max_length=2)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('blurry', 'Нечёткое фото'), ('expired', 'Документ просрочен'), ('mismatch', 'Данные не совпадают'), ('fake', 'Подозрение на подделку'), ('other', 'Другое')], max_length=20, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Верификация',
                'verbose_name_plural': 'KYC Верификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_wagered', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_won', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_reason', models.TextField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_wallets', to=settings.AUTH_USER_MODEL)),
                ('primary_currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='wallet.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(default=apps.wallet.models._generate_txn_id, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('bet', 'Ставка'), ('win', 'Выигрыш'), ('refund', 'Возврат'), ('bonus', 'Бонус'), ('referral', 'Реферальная комиссия'), ('conversion_debit', 'Конвертация (списание)'), ('conversion_credit', 'Конвертация (зачисление)'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка'), ('fee', 'Комиссия'), ('adjustment', 'Корректировка (админ)')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('balance_before', models.DecimalField(decimal_places=8, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='completed', max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('failed', 'Ошибка')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='wallet.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='wallet.currency')),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_credit', to='wallet.transaction')),
                ('debit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_debit', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Конвертация',
                'verbose_name_plural': 'Конвертации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('frozen', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Баланс валюты',
                'verbose_name_plural': 'Балансы валют',
            },
        ),
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('auto_withdrawal_limit_default', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=18)),
                ('auto_withdrawal_limit_verified', models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=18)),
                ('auto_withdrawal_limit_trusted', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=18)),
                ('kyc_required_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=18)),
                ('max_daily_withdrawal_usd', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=18)),
                ('new_account_withdrawal_delay_hours', models.IntegerField(default=24)),
                ('min_bets_before_withdrawal', models.IntegerField(default=0)),
                ('conversion_enabled', models.BooleanField(default=True)),
                ('registration_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('registration_bonus_currency', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'verbose_name': 'Настройки кошелька',
                'indexes': [models.Index(fields=['singleton_id'], name='wallet_wall_singlet_02efe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(default=apps.wallet.models._generate_withdrawal_id, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('crypto', 'Криптовалюта'), ('ewallet', 'Электронный кошелёк')], max_length=20)),
                ('payment_details', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('auto_approved', 'Автоматически одобрена'), ('manual_review', 'На ручной проверке'), ('approved', 'Одобрена'), ('processing', 'Обрабатывается'), ('completed', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена пользователем')], default='pending', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', '🟢 Низкий'), ('medium', '🟡 Средний'), ('high', '🔴 Высокий'), ('critical', '⛔ Критический')], default='low', max_length=10)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('auto_withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.wallet.models._withdrawal_expires_default)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.currency')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_wall_user_id_03e396_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_frozen'], name='wallet_wall_is_froz_e9a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__a053af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_4e9914_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='wallet_tran_type_fa9e01_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_a49b73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallet_tran_referen_4c93e3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='wallet_tran_transac_12527c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_usd__gte', 0)), name='transaction_amount_usd_non_negative'),
        ),
        migrations.AddIndex(
            model_name='walletbalance',
            index=models.Index(fields=['wallet', 'currency'], name='wallet_wall_wallet__bd57df_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.CheckConstraint(condition=models.Q(('available__gte', 0)), name='wallet_balance_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.CheckConstraint(condition=models.Q(('frozen__gte', 0)), name='wallet_balance_frozen_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='walletbalance',
            unique_together={('wallet', 'currency')},
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='wallet_with_status_f692e5_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['risk_level'], name='wallet_with_risk_le_616b81_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'created_at'], name='wallet_with_user_id_0bf433_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet', 'status'], name='wallet_with_wallet__b8c63b_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='withdrawal_net_amount_non_negative'),
        ),
    ]
