import hashlib
import hmac
import logging
import json
import time
import uuid
from decimal import Decimal, InvalidOperation
from functools import wraps

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth import get_user_model
from apps.wallet.models import Wallet, Currency
from apps.wallet.services.transaction_service import TransactionService, InsufficientFundsError

logger = logging.getLogger(__name__)
User = get_user_model()
CASINO_API_MAX_SKEW_SECONDS = 300


def casino_api_authenticated(view_func):
    """Authenticate engine requests with a timestamped HMAC and one-use request ID."""
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        secret = settings.CASINO_API_SECRET
        if len(secret.encode('utf-8')) < 32:
            return JsonResponse({'error': 'Casino API is not configured'}, status=503)

        timestamp = request.headers.get('X-Casino-Timestamp', '')
        request_id = request.headers.get('X-Casino-Request-Id', '')
        signature = request.headers.get('X-Casino-Signature', '')
        try:
            request_time = int(timestamp)
            parsed_request_id = uuid.UUID(request_id)
        except (TypeError, ValueError, AttributeError):
            return JsonResponse({'error': 'Invalid authentication headers'}, status=401)

        if str(parsed_request_id) != request_id or abs(time.time() - request_time) > CASINO_API_MAX_SKEW_SECONDS:
            return JsonResponse({'error': 'Expired or invalid request'}, status=401)

        body_hash = hashlib.sha256(request.body).hexdigest()
        message = '\n'.join((
            timestamp,
            request.method.upper(),
            request.get_full_path(),
            body_hash,
            request_id,
        ))
        expected_signature = hmac.new(
            secret.encode('utf-8'), message.encode('utf-8'), hashlib.sha256
        ).hexdigest()
        if not hmac.compare_digest(signature, expected_signature):
            return JsonResponse({'error': 'Invalid signature'}, status=401)

        if not cache.add(
            f'casino_api_request:{request_id}', True, timeout=CASINO_API_MAX_SKEW_SECONDS * 2
        ):
            return JsonResponse({'error': 'Request has already been processed'}, status=409)

        request.casino_request_id = request_id
        return view_func(request, *args, **kwargs)

    return wrapper


@casino_api_authenticated
@require_http_methods(["GET"])
def verify_sso(request):
    """
    Verifies a one-time SSO token generated by DOD.
    """
    token = request.GET.get('token')
    if not token:
        return JsonResponse({'error': 'Token required'}, status=400)
    
    user_id = cache.get(f"casino_sso_{token}")
    if user_id:
        # We don't delete immediately to allow for a few retries if PHP engine is slow
        return JsonResponse({'success': True, 'user_id': user_id})
    
    return JsonResponse({'error': 'Invalid or expired token'}, status=401)

def get_wallet_context(user_id, currency_code):
    try:
        user = User.objects.get(id=user_id)
        wallet = user.wallet
        currency = Currency.objects.get(code=currency_code)
        return user, wallet, currency
    except (
        User.DoesNotExist,
        Wallet.DoesNotExist,
        Currency.DoesNotExist,
        ValidationError,
        TypeError,
        ValueError,
    ):
        return None, None, None


@casino_api_authenticated
@require_http_methods(["GET"])
def get_balance(request):
    """
    Internal API to get user balance.
    PHP Engine calls this to display balance in-game.
    """
    user_id = request.GET.get('user_id')
    currency_code = request.GET.get('currency', 'USD')
    
    _, wallet, _ = get_wallet_context(user_id, currency_code)
    if not wallet:
        return JsonResponse({'error': 'Wallet or Currency not found'}, status=404)
    
    balance = wallet.get_balance(currency_code)
    return JsonResponse({'balance': float(balance), 'currency': currency_code})


@casino_api_authenticated
@require_http_methods(["POST"])
def place_bet(request):
    """
    Internal API to deduct bet amount.
    """
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    
    try:
        data = json.loads(request.body)
        if not isinstance(data, dict):
            return JsonResponse({'error': 'JSON object required'}, status=400)
        user_id = data.get('user_id')
        amount = Decimal(str(data.get('amount')))
        if not amount.is_finite() or amount <= 0:
            return JsonResponse({'error': 'Amount must be positive'}, status=400)
        currency_code = data.get('currency', 'USD')
        game_code = data.get('game_code', 'Unknown')
        
        _, wallet, _ = get_wallet_context(user_id, currency_code)
        if not wallet:
            return JsonResponse({'error': 'Wallet not found'}, status=404)
        
        # We use transaction service to handle debit logic
        TransactionService.withdraw(
            wallet,
            currency_code=currency_code,
            amount=amount,
            txn_type='bet',
            description=f'Stake in {game_code}',
            metadata={'game_code': game_code, 'source': 'ExternalEngine'},
            reference_type='casino_bet',
            reference_id=request.casino_request_id,
        )
        
        return JsonResponse({
            'success': True, 
            'new_balance': float(wallet.get_balance(currency_code))
        })
        
    except InsufficientFundsError:
        return JsonResponse({'error': 'Insufficient funds'}, status=400)
    except (json.JSONDecodeError, InvalidOperation, TypeError, ValueError):
        return JsonResponse({'error': 'Invalid request data'}, status=400)
    except Exception:
        logger.exception("Casino bet request failed")
        return JsonResponse({'error': 'Unable to process bet'}, status=500)


@casino_api_authenticated
@require_http_methods(["POST"])
def record_win(request):
    """
    Internal API to credit win amount.
    """
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    
    try:
        data = json.loads(request.body)
        if not isinstance(data, dict):
            return JsonResponse({'error': 'JSON object required'}, status=400)
        user_id = data.get('user_id')
        amount = Decimal(str(data.get('amount')))
        currency_code = data.get('currency', 'USD')
        game_code = data.get('game_code', 'Unknown')
        
        if not amount.is_finite():
            return JsonResponse({'error': 'Invalid amount'}, status=400)
        if amount <= 0:
            return JsonResponse({'success': True, 'message': 'Zero win ignored'})

        _, wallet, _ = get_wallet_context(user_id, currency_code)
        if not wallet:
            return JsonResponse({'error': 'Wallet not found'}, status=404)
        
        TransactionService.deposit(
            wallet,
            currency_code=currency_code,
            amount=amount,
            txn_type='win',
            description=f'Win in {game_code}',
            metadata={'game_code': game_code, 'source': 'ExternalEngine'},
            reference_type='casino_win',
            reference_id=request.casino_request_id,
        )
        
        return JsonResponse({
            'success': True, 
            'new_balance': float(wallet.get_balance(currency_code))
        })
        
    except (json.JSONDecodeError, InvalidOperation, TypeError, ValueError):
        return JsonResponse({'error': 'Invalid request data'}, status=400)
    except Exception:
        logger.exception("Casino win request failed")
        return JsonResponse({'error': 'Unable to process win'}, status=500)
