import uuid
import logging
import json
from decimal import Decimal
from django.core.cache import cache
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from apps.wallet.models import Wallet, Currency
from apps.wallet.services.transaction_service import TransactionService, InsufficientFundsError

logger = logging.getLogger(__name__)
User = get_user_model()

@csrf_exempt
def verify_sso(request):
    """
    Verifies a one-time SSO token generated by DOD.
    """
    token = request.GET.get('token')
    if not token:
        return JsonResponse({'error': 'Token required'}, status=400)
    
    user_id = cache.get(f"casino_sso_{token}")
    if user_id:
        # We don't delete immediately to allow for a few retries if PHP engine is slow
        return JsonResponse({'success': True, 'user_id': user_id})
    
    return JsonResponse({'error': 'Invalid or expired token'}, status=401)

def get_wallet_context(user_id, currency_code):
    try:
        user = User.objects.get(id=user_id)
        wallet = user.wallet
        currency = Currency.objects.get(code=currency_code)
        return user, wallet, currency
    except (User.DoesNotExist, Wallet.DoesNotExist, Currency.DoesNotExist):
        return None, None, None

@csrf_exempt
def get_balance(request):
    """
    Internal API to get user balance.
    PHP Engine calls this to display balance in-game.
    """
    user_id = request.GET.get('user_id')
    currency_code = request.GET.get('currency', 'USD')
    
    _, wallet, _ = get_wallet_context(user_id, currency_code)
    if not wallet:
        return JsonResponse({'error': 'Wallet or Currency not found'}, status=404)
    
    balance = wallet.get_balance(currency_code)
    return JsonResponse({'balance': float(balance), 'currency': currency_code})

@csrf_exempt
def place_bet(request):
    """
    Internal API to deduct bet amount.
    """
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    
    try:
        data = json.loads(request.body)
        user_id = data.get('user_id')
        amount = Decimal(str(data.get('amount')))
        currency_code = data.get('currency', 'USD')
        game_code = data.get('game_code', 'Unknown')
        
        _, wallet, _ = get_wallet_context(user_id, currency_code)
        if not wallet:
            return JsonResponse({'error': 'Wallet not found'}, status=404)
        
        # We use transaction service to handle debit logic
        TransactionService.withdraw(
            wallet,
            currency_code=currency_code,
            amount=amount,
            txn_type='bet',
            description=f'Stake in {game_code}',
            metadata={'game_code': game_code, 'source': 'ExternalEngine'}
        )
        
        return JsonResponse({
            'success': True, 
            'new_balance': float(wallet.get_balance(currency_code))
        })
        
    except InsufficientFundsError:
        return JsonResponse({'error': 'Insufficient funds'}, status=400)
    except Exception as e:
        logger.error(f"Casino Bet Error: {e}")
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
def record_win(request):
    """
    Internal API to credit win amount.
    """
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)
    
    try:
        data = json.loads(request.body)
        user_id = data.get('user_id')
        amount = Decimal(str(data.get('amount')))
        currency_code = data.get('currency', 'USD')
        game_code = data.get('game_code', 'Unknown')
        
        if amount <= 0:
            return JsonResponse({'success': True, 'message': 'Zero win ignored'})

        _, wallet, _ = get_wallet_context(user_id, currency_code)
        if not wallet:
            return JsonResponse({'error': 'Wallet not found'}, status=404)
        
        TransactionService.deposit(
            wallet,
            currency_code=currency_code,
            amount=amount,
            txn_type='win',
            description=f'Win in {game_code}',
            metadata={'game_code': game_code, 'source': 'ExternalEngine'}
        )
        
        return JsonResponse({
            'success': True, 
            'new_balance': float(wallet.get_balance(currency_code))
        })
        
    except Exception as e:
        logger.error(f"Casino Win Error: {e}")
        return JsonResponse({'error': str(e)}, status=500)
